name: Run Tests

on:
  push:
    branches: [ main, unit-tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Single Python version for faster testing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install test dependencies if they exist
        if [ -f requirements-test.txt ]; then
          pip install -r requirements-test.txt
        fi
        # Install coverage for test reporting
        pip install coverage pytest-cov
    
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --tb=short --cov=app --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Check code quality
      run: |
        # Basic syntax check
        python -m py_compile app/*.py
        python -m py_compile scripts/*.py
        echo "Code syntax check passed"
